version: '3.0'

services:
  redis: 
    container_name: "redis5.0"
    build: ./redis
    restart: always
    ports:
      - "6380:6379"

  mysql:
    container_name: "mysql"
    build: ./mysql
    restart: always
    ports:
      - "3307:3306"

  phpmyadmin:
    container_name: "phpmyadmin"
    links:
      - mysql
    build: ./phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      # - PMA_ARBITRARY=1 允许登录任何ip
    ports:
      - "8888:80"
    depends_on:
      - mysql
  
  # 使用 nginx 解决 phpmyadmin 的跨域问题 
  nginx:
    container_name: "nginx"
    links:
      - phpmyadmin
    build: ./nginx
    ports:
      - "8889:80"
    restart: always
    depends_on:
      - phpmyadmin