// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"cloud_disk/app/user/cmd/rpc/internal/logic"
	"cloud_disk/app/user/cmd/rpc/internal/svc"
	"cloud_disk/app/user/cmd/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServer) Register(ctx context.Context, in *pb.UserRegisterRequest) (*pb.UserRegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServer) EmailVerification(ctx context.Context, in *pb.EmailVerificationRequest) (*pb.EmailVerificationResponse, error) {
	l := logic.NewEmailVerificationLogic(ctx, s.svcCtx)
	return l.EmailVerification(in)
}

func (s *UserCenterServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenRequest) (*pb.RefreshTokenResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *UserCenterServer) GetIdentityWithToken(ctx context.Context, in *pb.GetIdentityWithTokenRequest) (*pb.GetIdentityWithTokenResponse, error) {
	l := logic.NewGetIdentityWithTokenLogic(ctx, s.svcCtx)
	return l.GetIdentityWithToken(in)
}
