// Code generated by goctl. DO NOT EDIT.
package types

type UserDetailRequest struct {
	Identify string `json:"identify"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
