// Code generated by goctl. DO NOT EDIT.
package types

type UserFolderCreateRequest struct {
	ParentId int    `json:"parent_id"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
}

type EditFileNameRequest struct {
	Identity string `json:"identity"` // 文件的唯一标识
	Name     string `json:"name"`     // 文件新名称
}

type EditFileNameResponse struct {
}

type UserFileListRequest struct {
	Id   int `json:"id,optional"` // 文件夹id
	Page int `json:"page,optional"`
	Size int `json:"size,optional"`
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int         `json:"count"`
}

type UserFile struct {
	Id                 int    `json:"id"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int    `json:"size"`
	Path               string `json:"path"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
}

type UserRepositoryRequest struct {
	ParentId           int    `json:"parent_id"`
	RepositoryIdentity string `json:"repository_identity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositoryResponse struct {
	Identity string `json:"identity"`
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Name     string `json:"name,optional"`
	Ext      string `json:"ext,optional"`
	Size     int64  `json:"size,optional"`
	Path     string `json:"path,optional"`
}

type UserRegisterRequest struct {
	Code     string `json:"code"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserRegisterResponse struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	Email    string `json:"email"`
}

type MailRegisterRequest struct {
	Email string `json:"email"`
}

type MailRegisterResponse struct {
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
