// Code generated by goctl. DO NOT EDIT!
// Source: email.proto

package emailcenter

import (
	"context"

	"cloud_disk/app/email/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendCodeRequest  = pb.SendCodeRequest
	SendCodeResponse = pb.SendCodeResponse

	EmailCenter interface {
		SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error)
	}

	defaultEmailCenter struct {
		cli zrpc.Client
	}
)

func NewEmailCenter(cli zrpc.Client) EmailCenter {
	return &defaultEmailCenter{
		cli: cli,
	}
}

func (m *defaultEmailCenter) SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error) {
	client := pb.NewEmailCenterClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}
