// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloud_disk/file/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/share",
				Handler: GetShareBasicDetailHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/repository/save",
				Handler: UserRepositorySaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/repository",
				Handler: UserFileListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/repository",
				Handler: EditFileNameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/folder",
				Handler: UserFolderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/file",
				Handler: UserFileDelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/file/move",
				Handler: UserFileMoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/share",
				Handler: ShareBasicCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/share/list",
				Handler: ShareBasicListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/upload/prepare",
				Handler: FileUploadPrepareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/chunk/upload",
				Handler: FileChunkUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/chunk/success",
				Handler: FileChunkSuccessHandler(serverCtx),
			},
		},
	)
}
